# Generated by Django 4.1.4 on 2022-12-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(default=1, max_length=100, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='full_name',
            field=models.CharField(default=1, max_length=100, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
