# Generated by Django 4.1.4 on 2022-12-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contactus_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='نام'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(default=1, max_length=200, verbose_name='last_name'),
            preserve_default=False,
        ),
    ]
