# Generated by Django 4.1.4 on 2023-02-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contactus_full_name_remove_contactus_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=100, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام کوچک'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
    ]
