# Generated by Django 4.1.4 on 2022-12-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0005_alter_product_datetime_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone', models.PositiveIntegerField(max_length=13, verbose_name='phone number')),
                ('address', models.TextField(verbose_name='address')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('is_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد شده')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='زمان اصلاح شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='products.product', verbose_name='Product')),
            ],
        ),
    ]
