# Generated by Django 4.1.4 on 2022-12-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('description', models.TextField(verbose_name='product description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='product price')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime_created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime_modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
        ),
    ]
