# Generated by Django 4.1.4 on 2022-12-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/product_image/', verbose_name='product image'),
            preserve_default=False,
        ),
    ]
