# Generated by Django 4.1.4 on 2022-12-31 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 15, 35, 18, 391123, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
