# Generated by Django 4.1.4 on 2022-12-31 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 15, 45, 4, 916142, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
