# Generated by Django 4.1.4 on 2023-01-01 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_categories_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 20, 25, 34, 44687, tzinfo=datetime.timezone.utc), verbose_name='datetime_created'),
        ),
    ]
