# Generated by Django 4.1.4 on 2023-05-03 06:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_datetime_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('position', models.IntegerField(verbose_name='position')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='category_parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': '',
                'ordering': ('parent__id', 'position'),
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'ordering': ('datetime_created',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ('published',), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 6, 3, 29, 291308, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime_created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='',
        ),
        migrations.AlterModelTable(
            name='product',
            table='',
        ),
    ]
