# Generated by Django 4.1.4 on 2023-05-03 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_category_delete_categories_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 16, 5, 8, 995274, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
