# Generated by Django 4.1.4 on 2023-05-15 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_category_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='products', to='products.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 16, 46, 8, 192748, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
