# Generated by Django 4.1.4 on 2023-05-16 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 7, 12, 43, 166611, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
    ]
