# Generated by Django 4.1.4 on 2023-08-06 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
        ('products', '0018_alter_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 17, 32, 37, 723930, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.CreateModel(
            name='ProductVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime_created')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.ipaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='visit',
            field=models.ManyToManyField(blank=True, related_name='visit', through='products.ProductVisits', to='visits.ipaddress', verbose_name='visit'),
        ),
    ]
