# Generated by Django 4.1.4 on 2023-08-07 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_published_productvisits_product_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='color name')),
                ('hex_code', models.CharField(max_length=6, verbose_name='color hex code')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_number', models.CharField(max_length=200, verbose_name='size number')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 14, 19, 39, 120330, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='products.color', verbose_name='colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='products.size', verbose_name='sizes'),
        ),
    ]
