# Generated by Django 4.1.4 on 2023-08-08 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_color_size_alter_product_published_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'managed': True, 'ordering': ('name',), 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'managed': True, 'ordering': ('size_number',), 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 20, 29, 7, 199730, tzinfo=datetime.timezone.utc), verbose_name='published'),
        ),
        migrations.AlterModelTable(
            name='color',
            table='',
        ),
        migrations.AlterModelTable(
            name='size',
            table='',
        ),
        migrations.CreateModel(
            name='ProductSizeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('قرمز', 'red'), ('آبی', 'blue'), ('مشکی', 'black'), ('طوسی', 'gray'), ('سبز', 'green')], max_length=250, verbose_name='color')),
                ('size', models.CharField(choices=[('بزرگ', 'big'), ('متوسط', 'normal'), ('کوچیک', 'small')], max_length=100, verbose_name='size')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size_color', to='products.product', verbose_name='product_size_color')),
            ],
        ),
    ]
